enum TodoStatus {
    COMPLETE
    IN_PROGRESS
    TODO
}

type TodoItem {
    title: String
    status: TodoStatus
}

type Query {
    todos: [TodoItem]
    # todo(idx: Int!): TodoItem
}

type Mutation {
    addTodo(title: String!): TodoItem
    todo(idx: Int!): TodoOps
}

type TodoOps {
    setStatus(status: TodoStatus!): TodoItem
}